version: "3.9"

services:
  app:
    build: .
    container_name: domainlookup_app_prod
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"  # Change port if you want to run alongside dev
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: domainlookup_db_prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

volumes:
  pgdata_prod:
